### ISSUE TITLE
datasets list in a collection is wrong when accesing a collection

### ISSUE THREAD

**Issue by rzido** [6aika/ckanext-collection#2]
When accesing a collection the datasets list (results) is wrong. It doesn't show datasets grouped on that collection. It lists all datasets.  

[Example](https://generic-qa.dataportaali.com/data/en_GB/collection/testikokoelma-2). This [dataset](https://generic-qa.dataportaali.com/data/en_GB/dataset/yllapitajan-lisaama-uusi-aineisto) belongs to another collection

**Comment by Zharktas** [comment]
Fixed in 25f99af8e86def16c4ab7ec1a33d0b9fa3a94fb3.

**Comment by rzido** [comment]
Thx @Zharktas for the quick fix.  This is a very useful extension and sixodp initiative is awesome.
